# This is an action for the VxWorks ROS 2 build.
# It downloads the WRLabs SDK and unpack it
#

name: 'Download SDK'
description: 'Downloads the SDK based on the provided JSON file, SDK name, and release version.'

inputs:
  json_file:
    description: 'Path to the JSON file'
    required: false
    default: '.github/workflows/data/wrsdks.json'
  name:
    description: 'Name of the SDK'
    required: false
    default: 'qemu'
  release:
    description: 'Release version'
    required: false
    default: '24.03'
  directory:
    description: 'Directory to download and extract the SDK'
    required: false
    default: '/tmp'

runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      run: |
        git clone ${{ env.GITHUB_SERVER_URL }}/${{ github.repository }} ${{ inputs.directory }}
      shell: bash

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install jsonschema
      shell: bash

    - name: Calculate URL
      id: calculate-url
      run: |
        cd ${{ inputs.directory }}
        python .github/workflows/scripts/parse_wrsdks.py "${{ inputs.json_file }}" "${{ inputs.name }}" "${{ inputs.release }}" > sdk-url.txt
        cat sdk-url.txt
      shell: bash

    - name: Store URL
      id: sdk-url
      run: |
        echo "SDK_URL=$(cat sdk-url.txt)" >> $GITHUB_ENV
        echo "FILENAME=$(basename $(cat sdk-url.txt))" >> $GITHUB_ENV
      shell: bash

    - name: Download SDK
      run: wget --no-check-certificate ${{ env.SDK_URL }} -P ${{ inputs.directory }}
      shell: bash

    - name: Extract SDK
      run: |
        mkdir -p ${{ inputs.directory }}/wrsdk
        cd  ${{ inputs.directory }}/wrsdk
        tar xvfj ${{ inputs.directory }}/${{ env.FILENAME }} --strip 1
      shell: bash

