# This is an action for the VxWorks ROS 2 build.
# It downloads the WRLabs SDK and unpack it
#

name: 'Download SDK'
description: 'Downloads the SDK based on the provided JSON file, SDK name, and release version.'

inputs:
  json_file:
    description: 'Path to the JSON file'
    required: false
    default: '.github/workflows/data/wrsdks.json'
  name:
    description: 'Name of the SDK'
    required: false
    default: 'qemu'
  release:
    description: 'Release version'
    required: false
    default: '24.03'
  directory:
    description: 'Directory to download the SDK'
    required: false
    default: '/tmp'

runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install jsonschema
      shell: bash

    - name: Calculate filename
      id: calculate-filename
      run: |
        cd ${{ github.workspace }}
        python .github/workflows/scripts/parse_wrsdks.py "${{ inputs.json_file }}" "${{ inputs.name }}" "${{ inputs.release }}" > filename.txt
        cat filename.txt
      shell: bash

    - name: Read filename
      id: read-filename
      run: echo "FILENAME=$(cat filename.txt)" >> $GITHUB_ENV
      shell: bash

    - name: Download SDK
      run: wget --no-check-certificate ${{ env.FILENAME }} -P ${{ inputs.directory }}
      shell: bash

