# This is an action for the VxWorks ROS 2 build.
# It downloads the WRLabs SDK and unpack it
#

name: 'Setup WRSDK'
description: 'Download and setup the VxWorks SDK'

inputs:
  json_file:
    description: 'JSON file that provides a description of all supported SDKs'
    required: false
    default: 'wrsdks.json'
  name:
    description: 'Name of the SDK'
    required: false
    default: 'qemu'
  release:
    description: 'VxWorks Release'
    required: false
    default: '24.03'
  directory:
    description: 'Directory to download and extract the SDK'
    required: false
    default: '/tmp'

runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install jsonschema
      shell: bash

    - name: Calculate SDK URL
      id: calculate-url
      run: |
        cd $GITHUB_ACTION_PATH
        python ./parse_wrsdks.py ${{ inputs.json_file }} ${{ inputs.name }} ${{ inputs.release }} > ${{ inputs.directory }}/sdk-url.txt
        cd ${{ inputs.directory }}
        cat sdk-url.txt
        echo SDK_URL=$(cat sdk-url.txt) >> $GITHUB_ENV
        echo FILENAME=$(basename $(cat sdk-url.txt)) >> $GITHUB_ENV
      shell: bash

    - name: Download SDK
      run: wget --no-check-certificate ${{ env.SDK_URL }} -P ${{ inputs.directory }}
      shell: bash

    - name: Extract SDK
      run: |
        mkdir -p ${{ inputs.directory }}/wrsdk
        cd  ${{ inputs.directory }}/wrsdk
        tar xvfj ${{ inputs.directory }}/${{ env.FILENAME }} --strip 1
      shell: bash

