name: 'VxWorks runner'
description: 'Composite action to run commands within a QEMU VxWorks environment'
inputs:
  sdk:
    description: 'SDK Name'
    required: false
    default: 'qemu'
  vxworks:
    description: 'VxWorks Release'
    required: false
    default: '24.03'
runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      id: install-dependencies
      run: |
        python -m pip install --upgrade pip
        pip install jsonschema
      shell: bash

    - name: Calculate SDK URL
      id: calculate-url
      run: |
        cd $GITHUB_ACTION_PATH
        python ./parse_wrsdks.py wrsdks.json ${{ inputs.sdk }} ${{ inputs.vxworks }} > /tmp/sdk-url.txt
        cd /tmp
        echo SDK_URL=$(cat sdk-url.txt) >> $GITHUB_ENV
        echo FILENAME=$(basename $(cat sdk-url.txt)) >> $GITHUB_ENV
      shell: bash

    - name: Download SDK
      id: download-sdk
      run: |
        if [ ! -f "/tmp/${{ env.FILENAME }}" ]; then
          wget --no-check-certificate ${{ env.SDK_URL }} -P /tmp
        else
          echo "SDK ${{ env.FILENAME }} already downloaded."
        fi
      shell: bash

    - name: Extract VxWorks
      id: extract-vxworks
      run: |
        if [ ! -f "/tmp/vxWorks" ]; then
          tar -xvjf /tmp/${{ env.FILENAME }} --strip-components=4 -C /tmp "wrsdk-vxworks7-${{ inputs.sdk }}/vxsdk/bsps/*/vxWorks"
          ls -la /tmp/vxWorks
        else
          echo "VxWorks already extracted."
        fi
      shell: bash
