# This is a workflow for the ARM 64-bit docker.
#
# The workflow can be started 
#  - manually

name: 'ARM 64-bit'

on:
  workflow_dispatch:

env:
  ARCH: arm64

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:

      - name: Setup
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu binfmt-support qemu-user-static
          sudo dpkg --add-architecture ${ARCH}
          sudo sed -i 's/deb h/deb [arch=amd64] h/g' /etc/apt/sources.list
          sudo add-apt-repository -n -s "deb [arch=$ARCH] http://ports.ubuntu.com/ubuntu-ports/ $(lsb_release -s -c) main universe restricted"
          sudo add-apt-repository -n -s "deb [arch=$ARCH] http://ports.ubuntu.com/ubuntu-ports $(lsb_release -s -c)-updates main universe restricted"
          sudo apt update

      - name: Check configuration
        run: |
          update-binfmts --display

      - name: Test
        run: |
          sudo apt-get update
          sudo apt-get install -y libc6:${ARCH} wget
          wget http://deb.debian.org/debian/pool/main/h/hello/hello_2.10-2_arm64.deb
          dpkg -x hello_2.10-2_arm64.deb /tmp/hello_arm64
          /tmp/hello_arm64/usr/bin/hello
          

      - name: Pull docker
        uses: addnab/docker-run-action@v3
        with:
          image: arm64v8/ubuntu
          options: --platform linux/arm64
          run:  |
            uname -a
