name: 'docker run test'

on: 
  workflow_dispatch:

jobs:
  docker_run:
    runs-on: ubuntu-20.04
    steps:

      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Build docker image
        uses: docker/build-push-action@v3
        with:
          context: Docker/vxbuild/.
          push: false
          tags: vxbuild:1.0

 #     - name: Build docker image
 #       uses: docker/build-push-action@v3
 #       with:
 #         context: Docker/vxros2build/.
 #         push: false
 #         tags: vxros2build:1.0

#      - name: Download a file
#        uses: carlosperate/download-file-action@v1
#        with:
#          file-url: 'https://labs.windriver.com/downloads/wrsdk-vxworks7-up2-1.7.tar.bz2'
#          location: '/tmp'
#          md5: 'c64fe30a496af66df771f2073f898276'

#      - name: Extract
#        run: |
#          cd /tmp
#          tar xvfj wrsdk-vxworks7-up2-1.7.tar.bz2

      - name: Extract
        run: |
          mkdir -p /tmp/wrsdk
          echo "This is a test" > /tmp/wrsdk/test

      - name: Setup environment
        run: |
          echo "UID=`id -u`" >> $GITHUB_ENV
          echo "GID=`id -g`" >> $GITHUB_ENV

      - name: Docker run
        uses: addnab/docker-run-action@v3
        with:
          image: vxbuild:1.0
          options: -e UID -u` -e GID -v ${{ github.workspace }}:/work -v /tmp/wrsdk:/wrsdk
          run:  |
             cat /wrsdk/test && id
