name: 'docker run test'

on: 
  workflow_dispatch:

jobs:
  docker_run:
    runs-on: ubuntu-20.04
    steps:

      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Build docker image
        uses: docker/build-push-action@v3
        with:
          context: Docker/vxbuild/.
          push: false
          tags: vxbuild:1.0

      - name: Build docker image
        uses: docker/build-push-action@v3
        with:
          context: Docker/vxros2build/.
          push: false
          tags: vxros2build:1.0

#      - name: Download a file
#        uses: carlosperate/download-file-action@v1
#        with:
#          file-url: 'https://labs.windriver.com/downloads/wrsdk-vxworks7-up2-1.7.tar.bz2'
#          location: '/tmp'
#          md5: 'c64fe30a496af66df771f2073f898276'

#      - name: Extract
#        run: |
#          cd /tmp
#          tar xvfj wrsdk-vxworks7-up2-1.7.tar.bz2

      - name: Extract
        run: |
          cd /tmp
          mkdir wrsdk-vxworks7-up2
          touch ./wrsdk-vxworks7-up2/test
          mv wrsdk-vxworks7-up2 wrsdk

      - name: Docker run
        uses: addnab/docker-run-action@v3
        with:
          image: vxros2build:1.0
          options: -v ${{ github.workspace }}:/work -v /tmp/wrsdk-vxworks7-up2:/wrsdk
          run:  |
             source /wrsdk/toolkit/wind_sdk_env.linux && make -C /work
