name: 'docker run test'

on: 
  workflow_dispatch:

jobs:
  docker_run:
    runs-on: ubuntu-20.04
    steps:

      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Build docker image
        uses: docker/build-push-action@v3
        with:
          context: Docker/vxbuild/.
          push: false
          tags: vxbuild:1.0

      - name: Build docker image
        uses: docker/build-push-action@v3
        with:
          context: Docker/vxros2build/.
          push: false
          tags: vxros2build:1.0


      - name: Docker run
        uses: addnab/docker-run-action@v3
        with:
          image: vxros2build:1.0
          options: -v ${{ github.workspace }}:/work
          run:  |
            ls /work
