# This is a workflow for the VxWorks ROS 2 build.
# It builds a ROS 2 VxWorks port against the VxWorks SDK 
#
# The workflow can be started 
#  - manually
#
# $ act -j download-sdk -P ubuntu-latest=nektos/act-environments-ubuntu:22.04 -e env.json
#
# $ cat env.json
# {
#   "event_name": "workflow_dispatch",
#   "inputs": {
#     "json_file": ".github/workflows/data/wrsdks.json",
#     "name": "qemu",
#     "release": "24.03"
#   }
# }

name: Download SDK

on:
  workflow_call:
  workflow_dispatch:
    inputs:
      json_file:
        description: 'Path to the JSON file'
        required: false
        default: '.github/workflows/data/wrsdks.json'
        type: string
      name:
        description: 'Name of the SDK'
        required: false
        default: 'qemu'
        type: string
      release:
        description: 'Release version'
        required: false
        default: '24.03'
        type: string
      directory:
        description: 'Directory to download the SDK'
        required: false
        default: '/tmp'
        type: string

jobs:
  download-sdk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install jsonschema

      - name: Calculate filename
        id: calculate-filename
        run: |
          python .github/workflows/scripts/parse_wrsdks.py "${{ inputs.json_file }}" "${{ inputs.name }}" "${{ inputs.release }}" > filename.txt
          cat filename.txt

      - name: Read filename
        id: read-filename
        run: echo "FILENAME=$(cat filename.txt)" >> $GITHUB_ENV

      - name: Download SDK
        run: wget --no-check-certificate ${{ env.FILENAME }} -P ${{ inputs.directory }}

