# This is a workflow for the VxWorks ROS 2 build.
# It builds a ROS 2 VxWorks port against the VxWorks SDK 
#
# The workflow can be started 
#  - manually

name: 'JSON file as a param'

on:
  workflow_dispatch:
    inputs:
      json_file_name:
        description: 'Name of the JSON file'
        required: true
        default: 'jsonfile-param-a.json'
jobs:
  build:
    strategy:
      matrix:
        ros_distro: [humble, iron, rolling]

    runs-on: ubuntu-22.04
    env:
      JSON_FILE: ${{ github.event.inputs.json_file_name }}
    continue-on-error: true
    steps:

      - name: Checks-out a branch ${{ github.ref }}
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Setup environment
        run: |
          sdk=`jq -r '[.vxros2build[] | select(.ros_distro == \"${{ matrix.ros_distro }}\") | {sdk} | .sdk][0]' ./.github/workflows/${{ env.JSON_FILE }}`
          echo "sdk=$sdk" >> $GITHUB_ENV
          echo "url=`jq -r '[.sdks[] | select(.name == \"${{ env.sdk }}\") | {url} | .url][0]' ./.github/workflows/sdks.json`" >> $GITHUB_ENV
          echo "script=`jq -r '[.sdks[] | select(.name == \"${{ env.sdk }}\") | {script} | .script][0]' ./.github/workflows/sdks.json`" >> $GITHUB_ENV
          echo "image=`jq -r '[.sdks[] | select(.name == \"${{ env.sdk }}\") | {image} | .image][0]' ./.github/workflows/sdks.json`" >> $GITHUB_ENV
          echo "ros_distro=`echo ${{ matrix.ros_distro }}`" >> $GITHUB_ENV

      - name: Download the ${{ matrix.sdk }} SDK
        uses: carlosperate/download-file-action@v1
        with:
          file-url: '${{ env.url }}'
          location: '/tmp'
