name: 'VxWorks ROS2 build'

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        branch: [dashing-release-SR0640]
        sdk: [wrsdk-vxworks7-up2-1.7, wrsdk-vxworks7-raspberrypi4b-1.0]
        include:
          - branch: dashing-release-22.03
            sdk: wrsdk-vxworks7-qemu-1.10
          - branch: humble-release-22.03
            sdk: wrsdk-vxworks7-qemu-1.10

    runs-on: ubuntu-20.04
    steps:

      - name: Checks-out a branch ${{ matrix.branch }}
        uses: actions/checkout@v2

      - name: Get uid and gid
        run: |
          echo "url: `jq '.vxros2build[] | select(.sdk == "${{ matrix.sdk }}") | {url} | .url' ./.github/workflows/vxros2build.json`"
