name: Build and Package OMNeT++ (Debian)

on:
  workflow_dispatch:
    inputs:
      omnetpp_version:
        description: 'OMNeT++ version to build'
        required: false
        default: '5.7.1'  # Default version if not provided
jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: debian:buster

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        apt-get update
        apt-get install -y build-essential clang bison flex perl python zlib1g-dev wget

    - name: Build OMNeT++
      run: |
        wget https://github.com/omnetpp/omnetpp/releases/download/omnetpp-${{ inputs.omnetpp_version }}/omnetpp-${{ inputs.omnetpp_version }}-src-linux.tgz
        tar -xvzf omnetpp-${{ inputs.omnetpp_version }}-src-linux.tgz
        cd omnetpp-${{ inputs.omnetpp_version }}
        source setenv
        ./configure
        make

    - name: Create Artifact
      run: |
        # Create a ZIP archive containing the built OMNeT++ files
        zip -r omnetpp-${{ inputs.omnetpp_version }}.zip omnetpp-${{ inputs.omnetpp_version }}

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: omnetpp-${{ inputs.omnetpp_version }}
        path: omnetpp-${{ inputs.omnetpp_version }}.zip
