name: 'RPI4 RT Kernel build'

# Controls when the workflow will run
on:
  workflow_dispatch:
  workflow_call:
    inputs:
      uname_r:
        description: 'raspi release in a form of <5.4.0-1058-raspi>'
        default: ''
        required: false
        type: string
      rt_patch:
        description: 'RT patch in a form of <5.4.177-rt69>'
        default: ''
        required: false
        type: string
      kernel_version:
        description: 'Raspi kernel version'
        default: '5.4.0'
        required: true
        type: string
      ubuntu_version:
        description: 'Ubuntu version'
        default: 'focal'
        required: true
        type: string
      lttng_version:
        description: 'LTTNG version'
        default: '2.13'
        required: true
        type: string

jobs:
  print-username:
    runs-on: ubuntu-latest

    steps:
      - name: Print the input name to STDOUT
        run: |
          echo uname_r is ${{ inputs.uname_r }}
          echo rt_patch is ${{ inputs.rt_patch }}
          echo kernel_version is ${{ inputs.kernel_version }}
          echo ubuntu_version is ${{ inputs.ubuntu_version }}
          echo lttng_version is ${{ inputs.lttng_version }}
